#!/usr/bin/env python3
"""Send morning briefing via Gmail SMTP."""

import os
import sys
import smtplib
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# Configuration
RECIPIENT_EMAIL = os.getenv("BRIEFING_EMAIL", "")
SENDER_EMAIL = os.getenv("BRIEFING_EMAIL", "")
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD", "")


def send_briefing(briefing_path: str):
    if not RECIPIENT_EMAIL or not GMAIL_APP_PASSWORD:
        print("❌ Set BRIEFING_EMAIL and GMAIL_APP_PASSWORD environment variables")
        print("   export BRIEFING_EMAIL='your.email@gmail.com'")
        print("   export GMAIL_APP_PASSWORD='your-16-char-app-password'")
        sys.exit(1)

    with open(briefing_path) as f:
        briefing_text = f.read()

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"📰 Debrief - {datetime.now().strftime('%B %d, %Y')}"
    msg["From"] = f"Debrief <{SENDER_EMAIL}>"
    msg["To"] = RECIPIENT_EMAIL

    # Convert markdown to basic HTML
    html_body = briefing_text.replace("\n", "<br>")
    html_body = f"""<html><body style="font-family: -apple-system, Arial, sans-serif;
    max-width: 800px; margin: 0 auto; padding: 20px; color: #1f2937;
    line-height: 1.6; font-size: 15px;">
    <div style="background: linear-gradient(135deg, #667eea, #764ba2);
    color: white; padding: 20px 30px; border-radius: 8px 8px 0 0;">
    <h1 style="margin:0; font-size: 22px;">📰 Debrief</h1>
    <p style="margin: 5px 0 0; font-size: 13px; opacity: 0.9;">
    {datetime.now().strftime('%B %d, %Y • %H:%M IST')}</p></div>
    <div style="padding: 25px 30px; background: #fff; border: 1px solid #e5e7eb;">
    {html_body}</div>
    <div style="background: #f9fafb; padding: 12px 30px; border: 1px solid #e5e7eb;
    font-size: 11px; color: #999;">Generated by Claude Code</div>
    </body></html>"""

    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(SENDER_EMAIL, GMAIL_APP_PASSWORD)
        server.sendmail(SENDER_EMAIL, RECIPIENT_EMAIL, msg.as_string())

    print(f"✅ Briefing emailed to {RECIPIENT_EMAIL}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 email_briefing.py <briefing_file.md>")
        sys.exit(1)
    send_briefing(sys.argv[1])
