#!/usr/bin/env python3
"""Daily morning briefing — Gemini 2.0 Flash + Google Search + Gmail SMTP."""

import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from google import genai
from google.genai.types import GenerateContentConfig, GoogleSearch, Tool

GEMINI_API_KEY = os.environ["GEMINI_API_KEY"]
GMAIL_ADDRESS = os.environ["GMAIL_ADDRESS"]
GMAIL_APP_PASSWORD = os.environ["GMAIL_APP_PASSWORD"]

RECIPIENTS = [GMAIL_ADDRESS, "rithikaveda@gmail.com"]

PROMPT = """You are Shashank's daily morning briefing assistant. Today is {date}.

Search the web for the LAST 24 HOURS of news and generate a sharp, opinionated briefing.

WHO THIS IS FOR:
Shashank — AI/ML engineer in Hyderabad, India. Works on LangGraph, RAG systems, agentic AI.
Projects: LockIn-KMP (Kotlin Multiplatform), GhostFlow (Tauri/Rust voice-to-text), AI Consulting.
Interests: agentic AI, Y Combinator, Anthropic, Kubernetes, n8n.

7 TOPICS (2-3 stories each, search each one):
1. Global Geopolitics — The Diplomat, CSIS, Peter Zeihan, breaking geopolitics news
2. Tech & Startups — TechCrunch, TLDR Tech, Stratechery, startup funding news
3. AI Developments — Anthropic, OpenAI, Google AI, new models, AI startups
4. India Politics & Startups — Inc42, The Ken India, YS Buzz, India startup news
5. Markets & Portfolio — Crunchbase funding, venture capital news, tech stocks
6. Culture & Internet — creator economy, Marketing Brew, internet discourse
7. Longevity & Health — Peter Attia, longevity research, GLP-1 news

FORMAT for each story:
**HEADLINE**
Summary: 2-3 sentences.
Why it matters: Shashank's angle (founder/AI/India/investment lens)
So what: One action to take.
Source: [link]

TONE: Sharp friend who's done the research. Opinionated. No filler. Flag what's "bigger than people think" or "overrated". Max 2500 words.

STRUCTURE:
📰 YOUR MORNING BRIEFING
Shashank | {date} | 06:00 IST
═══════════════════════════════════════
🌍 GLOBAL GEOPOLITICS
[stories]
═══════════════════════════════════════
💻 TECH & STARTUPS
[stories]
═══════════════════════════════════════
🤖 AI DEVELOPMENTS
[stories]
═══════════════════════════════════════
🇮🇳 INDIA POLITICS & STARTUPS
[stories]
═══════════════════════════════════════
📈 MARKETS & PORTFOLIO SIGNALS
[stories]
═══════════════════════════════════════
🎭 CULTURE, MEDIA & DISCOURSE
[stories]
═══════════════════════════════════════
❤️ LONGEVITY & HEALTH
[stories]
═══════════════════════════════════════
⭐ TOP 3 POSTS FROM X/YOUTUBE
[posts]
═══════════════════════════════════════
That's your briefing. Now go build something.
"""


def generate_briefing() -> str:
    client = genai.Client(api_key=GEMINI_API_KEY)
    date_str = datetime.now().strftime("%B %d, %Y")

    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=PROMPT.format(date=date_str),
        config=GenerateContentConfig(
            tools=[Tool(google_search=GoogleSearch())],
        ),
    )
    return response.text


def send_email(briefing: str):
    date_str = datetime.now().strftime("%B %d, %Y")

    html_body = briefing.replace("\n", "<br>").replace("**", "<strong>", 1)
    # Wrap alternating ** for bold
    i = 0
    result = []
    for part in briefing.split("**"):
        if i % 2 == 1:
            result.append(f"<strong>{part}</strong>")
        else:
            result.append(part.replace("\n", "<br>"))
        i += 1
    html_content = "".join(result)

    html = f"""<html><body style="font-family:-apple-system,Arial,sans-serif;
max-width:800px;margin:0 auto;padding:20px;color:#1f2937;line-height:1.6;font-size:15px">
<div style="background:linear-gradient(135deg,#667eea,#764ba2);color:white;
padding:20px 30px;border-radius:8px 8px 0 0">
<h1 style="margin:0;font-size:22px">📰 Debrief</h1>
<p style="margin:5px 0 0;font-size:13px;opacity:0.9">{date_str} • 06:00 IST</p></div>
<div style="padding:25px 30px;background:#fff;border:1px solid #e5e7eb">
{html_content}</div>
<div style="background:#f9fafb;padding:12px 30px;border:1px solid #e5e7eb;
font-size:11px;color:#999">Generated by Gemini 2.0 Flash + Google Search</div>
</body></html>"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"📰 Debrief — {date_str}"
    msg["From"] = f"Debrief <{GMAIL_ADDRESS}>"
    msg["To"] = ", ".join(RECIPIENTS)
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_ADDRESS, RECIPIENTS, msg.as_string())

    print(f"✅ Briefing sent to {', '.join(RECIPIENTS)}")


if __name__ == "__main__":
    print(f"🔍 Generating briefing for {datetime.now().strftime('%B %d, %Y')}...")
    briefing = generate_briefing()
    print("📧 Sending email...")
    send_email(briefing)
